package io.github.harshmittal.urlshortener.support;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;

/**
 * One bootstrap admin key per test JVM, generated by {@code scripts/new-admin-key.sh} (AC1). Its
 * hash becomes {@code BOOTSTRAP_ADMIN_KEY_HASH} for every integration-test context.
 */
public final class TestAdminKey {

    private static final Map<String, String> GENERATED = runScript();

    private TestAdminKey() {}

    public static String key() {
        return GENERATED.get("key");
    }

    public static String hash() {
        return GENERATED.get("hash");
    }

    private static Map<String, String> runScript() {
        try {
            Process process = new ProcessBuilder("scripts/new-admin-key.sh")
                    .redirectError(ProcessBuilder.Redirect.INHERIT)
                    .start();
            String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
            if (process.waitFor() != 0) {
                throw new IllegalStateException("scripts/new-admin-key.sh failed");
            }
            Map<String, String> values = new HashMap<>();
            for (String line : output.split("\n")) {
                int separator = line.indexOf('=');
                if (separator > 0) {
                    values.put(
                            line.substring(0, separator),
                            line.substring(separator + 1).trim());
                }
            }
            if (!values.containsKey("key") || !values.containsKey("hash")) {
                throw new IllegalStateException("scripts/new-admin-key.sh printed no key= and hash= lines");
            }
            return Map.copyOf(values);
        } catch (IOException e) {
            throw new IllegalStateException("Could not run scripts/new-admin-key.sh", e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("Interrupted while running scripts/new-admin-key.sh", e);
        }
    }
}
